name: Tag push
on:
  push:
     tags:
       - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run your first job
      run: |
        echo "This is the first job. Tag was pushed!"

  job2:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run your second job
      run: |
        echo "This is the second job. Tag was pushed!"

  job3:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/') && endsWith(github.ref, 'x.x.0')
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run your last job
      run: |
        echo "This is the last job. Tag was pushed and it is a minor version tag!"