name: Tag push
on:
  push:
     tags:
       - "[0-9]+.[0-9]+.[0-9]+"

env:
  GIT_TAG: ${{ github.ref_name }}

jobs:
  job1:
    runs-on: ubuntu-latest
    # outputs:
    #    MAJOR_VERSION: ${{ steps.versions.outputs.MAJOR_VERSION }}
    #    MINOR_VERSION: ${{ steps.versions.outputs.MINOR_VERSION }}
    #    PREVIOUS_MAJOR_VERSION: ${{ steps.versions.outputs.PREVIOUS_MAJOR_VERSION }}
    #    PREVIOUS_MINOR_VERSION: ${{ steps.versions.outputs.PREVIOUS_MINOR_VERSION }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run your first job
      run: |
        echo "This is the first job. Tag was pushed!"
    # - name: get versions
    #   id: versions
    #   run: |
    #       MAJOR_VERSION=$(echo $GIT_TAG | cut -d'.' -f1)
    #       MINOR_VERSION=$(echo $GIT_TAG | cut -d'.' -f2)
    #       PREVIOUS_TAG=$(git describe --tags --abbrev=0 ${GITHUB_SHA}^)
    #       PREVIOUS_MAJOR_VERSION=$(echo $PREVIOUS_TAG | cut -d'.' -f1)
    #       PREVIOUS_MINOR_VERSION=$(echo $PREVIOUS_TAG | cut -d'.' -f2)
    #       echo "MAJOR_VERSION=$MAJOR_VERSION" >> $GITHUB_OUTPUT
    #       echo "MINOR_VERSION=$MINOR_VERSION" >> $GITHUB_OUTPUT
    #       echo "PREVIOUS_MAJOR_VERSION=$PREVIOUS_MAJOR_VERSION" >> $GITHUB_OUTPUT
    #       echo "PREVIOUS_MINOR_VERSION=$PREVIOUS_MINOR_VERSION" >> $GITHUB_OUTPUT

  job2:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run your second job
      run: |
        echo "This is the second job. Tag was pushed!"

  job3:
    runs-on: ubuntu-latest
    if: |
      tag_old=`echo "$GITHUB_REF" | sed -E 's#refs/tags/(.*)#\1#'`
      tag_new=`echo "$GIT_TAG" | cut -c 1-10`
      version_old=`echo $tag_old | sed -E 's/([0-9]+)\.([0-9]+)\.([0-9]+)/\1.\2/'`
      version_new=`echo $tag_new | sed -E 's/([0-9]+)\.([0-9]+)\.([0-9]+)/\1.\2/'`
      [ "$version_old" != "$version_new" ]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run your last job
      run: |
        echo "This is the last job. Tag was pushed and it is a minor version tag!"