name: Tag push

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
        GIT_TAG: ${{ steps.generate-tag.outputs.git_tag }}
        GITHUB_LATEST_TAG: ${{ steps.generate-tag.outputs.lates_git_tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate git tag
        id: generate-tag
        run: |
            GITHUB_LATEST_RELEASE=$(git tag -l --sort -version:refname | grep -E '^[0-9]+\.[0-9]+\.[0-9]$' | head -n 1)
            INCREMENTED_GITHUB_LATEST_RELEASE=$(echo ${GITHUB_LATEST_RELEASE} | awk -F. -v OFS=. 'NF==1{print ++$NF}; NF>1{if(length($NF+1)>length($NF))$(NF-1)++; $NF=sprintf("%0*d", length($NF), ($NF+1)%(10^length($NF))); print}')
            GIT_TAG=$(echo $INCREMENTED_GITHUB_LATEST_RELEASE)
            echo "git_tag=$GIT_TAG" >> $GITHUB_OUTPUT
            echo "lates_git_tag=$GITHUB_LATEST_RELEASE" >> $GITHUB_OUTPUT

      - name: Create git tag
        run: |
            git tag "${{ env.GIT_TAG }}" "${{ github.sha }}"
            git push origin "${{ env.GIT_TAG }}"
        env:
            GIT_TAG: ${{ steps.generate-tag.outputs.git_tag }}

      - name: Get commits
        id: commits
        run: | 
            COMMITS=$(git log --format=%s ${{ env.GITHUB_LATEST_TAG }}..${{ env.NEW_GIT_TAG }})
            # echo "COMMITS=$COMMITS" >> $GITHUB_ENV
            
            {
                echo 'COMMITS<<EOF'
                $COMMITS
                echo EOF
            } >> "$GITHUB_ENV"
        env:
            NEW_GIT_TAG: ${{ steps.generate-tag.outputs.git_tag }}
            GITHUB_LATEST_TAG: ${{ steps.generate-tag.outputs.lates_git_tag }}

      - name: Create git release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.generate-tag.outputs.git_tag }}
          commit: ${{ github.sha }}
          name: ${{ steps.generate-tag.outputs.git_tag }}     
          generateReleaseNotes: true
          body: ${{ env.COMMITS }}